# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elevage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSanitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_incident', models.DateField()),
                ('description', models.TextField()),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('resolu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bande_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevage.bandechair')),
                ('bande_pondeuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevage.bandepondeuse')),
                ('signale_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biosecurite_incidents_sanitaires',
                'indexes': [models.Index(fields=['resolu'], name='idx_incidents_resolu')],
                'constraints': [models.CheckConstraint(condition=models.Q(('bande_pondeuse__isnull', False), ('bande_chair__isnull', False), _connector='OR'), name='chk_bande_cible_incident')],
            },
        ),
        migrations.CreateModel(
            name='InterventionVeterinaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_intervention', models.DateField()),
                ('type_intervention', models.CharField(choices=[('vaccination', 'Vaccination'), ('traitement', 'Traitement'), ('visite_veterinaire', 'Visite vétérinaire')], max_length=30)),
                ('produit', models.CharField(blank=True, max_length=150, null=True)),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bande_chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevage.bandechair')),
                ('bande_pondeuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevage.bandepondeuse')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biosecurite_interventions_veterinaires',
                'indexes': [models.Index(fields=['date_intervention'], name='idx_interventions_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('bande_pondeuse__isnull', False), ('bande_chair__isnull', False), _connector='OR'), name='chk_bande_cible')],
            },
        ),
    ]
