# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('aliment', 'Aliment'), ('medicament', 'Médicament'), ('vaccin', 'Vaccin'), ('desinfectant', 'Désinfectant'), ('emballage', 'Emballage'), ('plateau_oeufs', "Plateau d'œufs"), ('materiel', 'Matériel'), ('piece_rechange', 'Pièce de rechange'), ('autre', 'Autre')], max_length=20)),
                ('unite', models.CharField(max_length=20)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_articles',
                'constraints': [models.UniqueConstraint(fields=('nom', 'categorie'), name='uq_article_nom_categorie')],
            },
        ),
        migrations.CreateModel(
            name='InventairePhysique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inventaire', models.DateField()),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_physique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecart', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantite_physique'), '-', models.F('quantite_theorique')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='stock.article')),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_inventaires_physiques',
                'constraints': [models.UniqueConstraint(fields=('article', 'date_inventaire'), name='uq_inventaire_article_date')],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_document', models.CharField(blank=True, max_length=100, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_mouvements',
                'indexes': [models.Index(fields=['article', 'date_mouvement'], name='idx_mouvements_article_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='chk_quantite_mouvement_positive')],
            },
        ),
    ]
