# Generated by Django 6.1.1 on 2026-09-24 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventairephysique",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantite_theorique", models.F("quantite_physique")),
                    ("justification__isnull", False),
                    _connector="OR",
                ),
                name="chk_justification_si_ecart",
            ),
        ),
    ]
