# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_depense', models.DateField()),
                ('categorie', models.CharField(choices=[('aliment', 'Aliment'), ('medicament_soins', 'Médicaments & soins'), ('salaires', 'Salaires'), ('eau_electricite', 'Eau & électricité'), ('transport', 'Transport'), ('entretien', 'Entretien'), ('emballage', 'Emballage'), ('autre', 'Autre')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_depense', models.CharField(choices=[('courante', 'Courante'), ('exceptionnelle', 'Exceptionnelle'), ('investissement', 'Investissement')], default='courante', max_length=20)),
                ('justificatif_url', models.URLField(blank=True, max_length=500, null=True)),
                ('statut_approbation', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('non_requise', 'Non requise')], default='non_requise', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_depenses',
                'indexes': [models.Index(fields=['date_depense'], name='idx_depenses_date'), models.Index(fields=['categorie'], name='idx_depenses_categorie')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type_depense', 'investissement'), _negated=True), ('justificatif_url__isnull', False), _connector='OR'), name='chk_justificatif_investissement')],
            },
        ),
    ]
