# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('restaurant', 'Restaurant'), ('hotel', 'Hôtel'), ('supermarche', 'Supermarché'), ('revendeur', 'Revendeur'), ('boulangerie', 'Boulangerie'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ventes_clients',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit')], max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('montant_total'), '-', models.F('montant_encaisse')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='ventes.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventes_ventes',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=150)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ligne', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantite'), '*', models.F('prix_unitaire')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'db_table': 'ventes_lignes',
            },
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['client', 'date_vente'], name='idx_ventes_client_date'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.CheckConstraint(condition=models.Q(('montant_encaisse__lte', models.F('montant_total'))), name='chk_encaisse_inferieur_total'),
        ),
    ]
