# Generated by Django 6.1.1 on 2026-09-27 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vente",
            name="date_vente",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
