# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('entite', models.CharField(max_length=100)),
                ('entite_id', models.UUIDField(blank=True, null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_journal',
                'indexes': [models.Index(fields=['entite', 'entite_id'], name='idx_audit_entite'), models.Index(fields=['date_action'], name='idx_audit_date')],
            },
        ),
    ]
