# Generated by Django 6.1.1 on 2026-09-16 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandeChair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField()),
                ('effectif_initial', models.PositiveIntegerField()),
                ('souche', models.CharField(blank=True, max_length=100, null=True)),
                ('poids_initial_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='active', max_length=20)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('nombre_vendu', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_vendu_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chiffre_affaires', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elevage_bandes_chair',
                'constraints': [models.CheckConstraint(condition=models.Q(('effectif_initial__gt', 0)), name='chk_effectif_initial_chair_positif')],
            },
        ),
        migrations.CreateModel(
            name='BandePondeuse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('date_mise_en_place', models.DateField()),
                ('effectif_initial', models.PositiveIntegerField()),
                ('souche', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elevage_bandes_pondeuses',
                'constraints': [models.CheckConstraint(condition=models.Q(('effectif_initial__gt', 0)), name='chk_effectif_initial_positif')],
            },
        ),
        migrations.CreateModel(
            name='SuiviChair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('poids_moyen_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('aliment_distribue_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mortalite', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='elevage.bandechair')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elevage_suivi_chair',
                'constraints': [models.UniqueConstraint(fields=('bande', 'date_suivi'), name='uq_suivi_chair_bande_date')],
            },
        ),
        migrations.CreateModel(
            name='SuiviPondeuse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('effectif_debut', models.PositiveIntegerField()),
                ('mortalite', models.PositiveIntegerField(default=0)),
                ('aliment_distribue_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eau_consommee_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('oeufs_produits', models.PositiveIntegerField(default=0)),
                ('oeufs_casses', models.PositiveIntegerField(default=0)),
                ('oeufs_vendus', models.PositiveIntegerField(default=0)),
                ('stock_oeufs_restant', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='elevage.bandepondeuse')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elevage_suivi_pondeuse',
                'indexes': [models.Index(fields=['bande', 'date_suivi'], name='idx_suivi_pondeuse_bande_date')],
                'constraints': [models.UniqueConstraint(fields=('bande', 'date_suivi'), name='uq_suivi_pondeuse_bande_date')],
            },
        ),
    ]
